### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [raflemakt/rickroll_sensehat#1]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by raflemakt** [comment]
I generally support FSF and the GPL license, but don't you think a more permissive license would make more sense here? This code is a simple hack that I suggest people can simply add to their own python scripts. Also, I have no experience with adding licenses so I'm not sure how that would work since I'm importing a couple of builtin python modules.

**Comment by TechnologyClassroom** [comment]
Permissive would be fine too.  In general, I choose copyleft over permissive because you never know what someone will do with a project.
